version: '3.12'
services:
  server:
    build: ./Server
    ports:
      - "12345:12345"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
  client:
    build: ./Client
    depends_on:
      - server
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true